# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Bind interface to implementation (Hexagonal Architecture)
    App\Task\Domain\Port\TaskRepositoryInterface:
        class: App\Task\Infrastructure\Persistence\Doctrine\DoctrineTaskRepository

    App\Task\Domain\Port\CurrentUserProviderInterface:
        class: App\Task\Infrastructure\Security\SymfonyCurrentUserProvider

    App\Task\Domain\Port\AuthorizationInterface:
        class: App\Task\Infrastructure\Security\SymfonyAuthorizationAdapter

    App\User\Domain\Port\UserRepositoryInterface:
        class: App\User\Infrastructure\Persistence\DoctrineUserRepository

    App\User\Domain\Port\PasswordHasherInterface:
        class: App\User\Infrastructure\Security\SymfonyPasswordHasher

    # Make commands public for custom console application
    App\Task\Presentation\Cli\Command\CreateTaskCommand:
        public: true

    App\Task\Presentation\Cli\Command\GetTasksCommand:
        public: true

    App\Task\Presentation\Cli\Command\CompleteTaskCommand:
        public: true

    App\Task\Presentation\Cli\Command\DeleteTaskCommand:
        public: true

    App\Task\Presentation\Cli\Command\AssignTaskCommand:
        public: true

    App\User\Presentation\Cli\Command\CreateUserCommand:
        public: true

    App\User\Presentation\Cli\Command\GetUsersCommand:
        public: true

    App\User\Presentation\Cli\Command\DeleteUserCommand:
        public: true
